all:
	cc main.c polecenia.c mapa.c ex.c -lcurl -o projekt ../cJSON/cjson.o

test:
	cc main.c projekt.c ex.c mapa.c ex.c -lcurl -o projekt ../cJSON/cjson.o

move:


left:


right:


explore:
